import { group } from "console";

export const FOUNDATION_MENU = [
  {
    group: "Foundation (Basics)",
    category: "basic",
    items: [
      { name: "Primary Tcode", slug: "primary-tcode", url: "/sap-tm/foundation/basic/primary-tcode" },
      { name: "Embedded vs Side Car TM", slug: "embedded-sidecar", url: "/sap-tm/foundation/basic/embedded-sidecar" },
      { name: "Business Partner", slug: "business-partner", url: "/sap-tm/foundation/basic/business-partner" },
      { name: "Plant and TM Relation", slug: "plant-tm-relation", url: "/sap-tm/foundation/basic/plant-tm-relation" },
      { name: "Transportation Zone", slug: "transportation-zone", url: "/sap-tm/foundation/basic/transportation-zone" },
      { name: "Direct & Postal Code Zone", slug: "direct-and-postal-code-zone", url: "/sap-tm/foundation/basic/direct-and-postal-code-zone" },
      { name: "Transportation Lane", slug: "transportation-lane", url: "/sap-tm/foundation/basic/transportation-lane" },
      { name: "Means of Transport", slug: "mtr", url: "/sap-tm/foundation/basic/mtr" },
      { name: "Vehicle & Handling Resource", slug: "vehicle-handling-resource", url: "/sap-tm/foundation/basic/vehicle-handling-resource" },
      { name: "Passive Resource", slug: "passive-resource", url: "/sap-tm/foundation/basic/passive-resource" },
      { name: "Planning and Execution Organization", slug: "plan-exe-org", url: "/sap-tm/foundation/basic/plan-exe-org" },
      { name: "Execution Group", slug: "exe-grp", url: "/sap-tm/foundation/basic/exe-grp" },
      { name: "Purchase Org Mapping", slug: "map-purchase-org", url: "/sap-tm/foundation/basic/map-purchase-org" },
      { name: "Create Location", slug: "create-location", url: "/sap-tm/foundation/basic/create-location" },
      { name: "Create Business Partner", slug: "create-bp", url: "/sap-tm/foundation/basic/create-bp" },
      { name: "UN/LOCODE", slug: "un-locode", url: "/sap-tm/foundation/basic/un-locode" },
      { name: "Transportation Zones", slug: "transportation-zones", url: "/sap-tm/foundation/basic/transportation-zones" },
      { name: "TM Model (MAS)", slug: "tm-model-mas", url: "/sap-tm/foundation/basic/tm-model-mas" },
      { name: "TM Calendars", slug: "tm-calendars", url: "/sap-tm/foundation/basic/tm-calendars" },
      { name: "Incompatibilities", slug: "incompatibilities", url: "/sap-tm/foundation/basic/incompatibilities" },
      { name: "Carrier Definition", slug: "carrier-definition", url: "/sap-tm/foundation/basic/carrier-definition" },
      { name: "Shipper vs LSP", slug: "shipper-vs-lsp", url: "/sap-tm/foundation/basic/shipper-vs-lsp" },
      { name: "Hub Locations", slug: "hub-location", url: "/sap-tm/foundation/basic/hub-location" },
      { name: "Gateway Locations", slug: "gateway-location", url: "/sap-tm/foundation/basic/gateway-location" },
      { name: "Transshipment Points", slug: "transshipment-location", url: "/sap-tm/foundation/basic/transshipment-location" },
      { name: "Container Check Digit", slug: "container-check-digit", url: "/sap-tm/foundation/basic/container-check-digit" },
      { name: "Transport Modes", slug: "transportation-modes", url: "/sap-tm/foundation/basic/transportation-modes" },
      { name: "FTL vs LTL", slug: "ftl-vs-ltl", url: "/sap-tm/foundation/basic/ftl-vs-ltl" },
      { name: "Product Master", slug: "product-master", url: "/sap-tm/foundation/basic/product-master" },
      { name: "Product CIF Integration", slug: "product-cif-integration", url: "/sap-tm/foundation/basic/product-cif-integration" },
      { name: "Location General Data", slug: "location-general-data", url: "/sap-tm/foundation/basic/location-general-data" },
      { name: "One-Time Location", slug: "one-time-location", url: "/sap-tm/foundation/basic/one-time-location" },
      { name: "Default Routes", slug: "default-route", url: "/sap-tm/foundation/basic/default-route" },
      { name: "Schedule vs Lane", slug: "schedule-vs-lane", url: "/sap-tm/foundation/basic/schedule-vs-lane" },
      { name: "Ocean Voyage", slug: "ocean-voyage", url: "/sap-tm/foundation/basic/ocean-voyage" },
      { name: "Air Flight", slug: "air-flight", url: "/sap-tm/foundation/basic/air-flight" },
      { name: "GIS Integration", slug: "gis-integration", url: "/sap-tm/foundation/basic/gis-integration" },
      { name: "Distance Determination (DDD)", slug: "distance-duration-determination", url: "/sap-tm/foundation/basic/distance-duration-determination" },
      { name: "Geocoding", slug: "geocoding", url: "/sap-tm/foundation/basic/geocoding" },
      { name: "Network Cockpit", slug: "transportation-network-cockpit", url: "/sap-tm/foundation/basic/transportation-network-cockpit" }
    ]
  },
  {
    group: "Foundation (Moderate)",
    category: "moderate",
    items: [
      { name: "Map Shipping Pt to Loc", slug: "map-shipping-point-to-location", url: "/sap-tm/foundation/moderate/map-shipping-point-to-location" },
      { name: "Define Means of Transport", slug: "define-means-of-transport", url: "/sap-tm/foundation/moderate/define-means-of-transport" },
      { name: "Link MTr to Vehicle Resource", slug: "link-mtr-to-resource", url: "/sap-tm/foundation/moderate/link-mtr-to-resource" },
      { name: "Missing Transp. Lane", slug: "missing-transportation-lane", url: "/sap-tm/foundation/moderate/missing-transportation-lane" },
      { name: "BP Blocking Logic", slug: "bp-blocking-logic", url: "/sap-tm/foundation/moderate/bp-blocking-logic" },
      { name: "Lane Determination Logic", slug: "lane-determination-logic", url: "/sap-tm/foundation/moderate/lane-determination-logic" },
      { name: "Hierarchical Zones", slug: "hierarchical-zone-structure", url: "/sap-tm/foundation/moderate/hierarchical-zone-structure" },
      { name: "MTr Average Speed", slug: "mtr-average-speed", url: "/sap-tm/foundation/moderate/mtr-average-speed" },
      { name: "Vehicle Resource Prereqs", slug: "vehicle-resource-prerequisites", url: "/sap-tm/foundation/moderate/vehicle-resource-prerequisites" },
      { name: "Location Operating Hours", slug: "location-operating-hours", url: "/sap-tm/foundation/moderate/location-operating-hours" },
      { name: "Loading/Unloading Duration", slug: "loading-unloading-duration", url: "/sap-tm/foundation/moderate/loading-unloading-duration" },
      { name: "Coupling/Uncoupling Duration", slug: "coupling-uncoupling-duration", url: "/sap-tm/foundation/moderate/coupling-uncoupling-duration" },
      { name: "Map Mat. Grp to Commodity", slug: "map-material-group-commodity", url: "/sap-tm/foundation/moderate/map-material-group-commodity" },
      { name: "Product UoM Conversions", slug: "product-uom-conversions", url: "/sap-tm/foundation/moderate/product-uom-conversions" },
      { name: "Restrict MTr in Zone", slug: "restrict-mtr-zone", url: "/sap-tm/foundation/moderate/restrict-mtr-zone" },
      { name: "Carrier Selection Settings", slug: "carrier-selection-settings", url: "/sap-tm/foundation/moderate/carrier-selection-settings" },
      { name: "Create Network View", slug: "create-network-view", url: "/sap-tm/foundation/moderate/create-network-view" },
      { name: "Trade Lane Purpose", slug: "trade-lane-purpose", url: "/sap-tm/foundation/moderate/trade-lane-purpose" },
      { name: "Lane Distance Buffer", slug: "lane-distance-buffer", url: "/sap-tm/foundation/moderate/lane-distance-buffer" },
      { name: "Equipment Groups & Types", slug: "equipment-groups-types", url: "/sap-tm/foundation/moderate/equipment-groups-types" },
      { name: "IGD vs GIS Distance", slug: "igd-vs-gis-distance", url: "/sap-tm/foundation/moderate/igd-vs-gis-distance" },
      { name: "Loading Point Calendar", slug: "loading-point-calendar", url: "/sap-tm/foundation/moderate/loading-point-calendar" },
      { name: "Fix Location Coordinates", slug: "fix-location-coordinates", url: "/sap-tm/foundation/moderate/fix-location-coordinates" },
      { name: "MTr Hierarchy", slug: "means-of-transport-hierarchy", url: "/sap-tm/foundation/moderate/means-of-transport-hierarchy" },
      { name: "Create Forwarding Agent", slug: "create-forwarding-agent", url: "/sap-tm/foundation/moderate/create-forwarding-agent" },
      { name: "Maintain SCAC Code", slug: "maintain-scac-code", url: "/sap-tm/foundation/moderate/maintain-scac-code" },
      { name: "BP Identification Tab", slug: "bp-identification-tab", url: "/sap-tm/foundation/moderate/bp-identification-tab" },
      { name: "FU Number Ranges", slug: "fu-number-ranges", url: "/sap-tm/foundation/moderate/fu-number-ranges" },
      { name: "Create Resource Class", slug: "create-resource-class", url: "/sap-tm/foundation/moderate/create-resource-class" },
      { name: "Link Driver to Home Base", slug: "link-driver-location", url: "/sap-tm/foundation/moderate/link-driver-location" },
      { name: "Planning Profile Basics", slug: "planning-profile-basics", url: "/sap-tm/foundation/moderate/planning-profile-basics" },
      { name: "GIS Services Setup", slug: "gis-services-setup", url: "/sap-tm/foundation/moderate/gis-services-setup" },
      { name: "Material Transp. Group", slug: "transportation-group-impact", url: "/sap-tm/foundation/moderate/transportation-group-impact" },
      { name: "Dangerous Goods Master", slug: "dangerous-goods-master-data", url: "/sap-tm/foundation/moderate/dangerous-goods-master-data" },
      { name: "IATA Code Definition", slug: "iata-code-definition", url: "/sap-tm/foundation/moderate/iata-code-definition" },
      { name: "Setup Location Aliases", slug: "setup-location-aliases", url: "/sap-tm/foundation/moderate/setup-location-aliases" },
      { name: "Location Handling Capacities", slug: "location-handling-capacities", url: "/sap-tm/foundation/moderate/location-handling-capacities" },
      { name: "Schedule Periodicity", slug: "schedule-periodicity", url: "/sap-tm/foundation/moderate/schedule-periodicity" },
      { name: "Lane Cost Functions", slug: "lane-cost-functions", url: "/sap-tm/foundation/moderate/lane-cost-functions" },
      { name: "Resource Org Assignment", slug: "resource-org-assignment", url: "/sap-tm/foundation/moderate/resource-org-assignment" }
    ]
  },
  {
    group: "Foundation (Advanced)",
    category: "advance",
    items: [
      { name: "Optimizer Lane Debugging", slug: "optimizer-lane-checks", url: "/sap-tm/foundation/advance/optimizer-lane-checks" },
      { name: "Troubleshoot Route Error", slug: "troubleshoot-route-error", url: "/sap-tm/foundation/advance/troubleshoot-route-error" },
      { name: "GIS Fallback Logic", slug: "gis-fallback-logic", url: "/sap-tm/foundation/advance/gis-fallback-logic" },
      { name: "Postal Code Optimization", slug: "postal-code-optimization", url: "/sap-tm/foundation/advance/postal-code-optimization" },
      { name: "Optimizer MTr Performance", slug: "optimizer-mtr-performance", url: "/sap-tm/foundation/advance/optimizer-mtr-performance" },

      // Complex Modeling
      { name: "Multi-Compartment Truck", slug: "multi-compartment-truck", url: "/sap-tm/foundation/advance/multi-compartment-truck" },
      { name: "Truck vs Trailer Zones", slug: "truck-trailer-zone-access", url: "/sap-tm/foundation/advance/truck-trailer-zone-access" },
      { name: "Tug and Barge Model", slug: "tug-and-barge-model", url: "/sap-tm/foundation/advance/tug-and-barge-model" },
      { name: "Cross-Dock Modeling", slug: "cross-dock-modeling", url: "/sap-tm/foundation/advance/cross-dock-modeling" },
      { name: "Virtual Location Setup", slug: "virtual-location-setup", url: "/sap-tm/foundation/advance/virtual-location-setup" },

      // Integration & Data Logic
      { name: "BP Address Update Sync", slug: "bp-address-sync-tm", url: "/sap-tm/foundation/advance/bp-address-sync-tm" },
      { name: "Business System Group", slug: "business-system-group", url: "/sap-tm/foundation/advance/business-system-group" },
      { name: "Shipping Point Logic", slug: "shipping-point-determination", url: "/sap-tm/foundation/advance/shipping-point-determination" },
      { name: "BAdI Master Data Download", slug: "badi-master-data-download", url: "/sap-tm/foundation/advance/badi-master-data-download" },

      // Advanced Configuration
      { name: "Intra vs Zone Lanes", slug: "intra-vs-zone-lanes", url: "/sap-tm/foundation/advance/intra-vs-zone-lanes" },
      { name: "Conditions for Lanes", slug: "conditions-lane-determination", url: "/sap-tm/foundation/advance/conditions-lane-determination" },
      { name: "Custom Attribute Zones", slug: "custom-attribute-zones", url: "/sap-tm/foundation/advance/custom-attribute-zones" },
      { name: "Closure vs Cut-off Time", slug: "closure-vs-cutoff-time", url: "/sap-tm/foundation/advance/closure-vs-cutoff-time" },

      // Technical / Tables
      { name: "TM Location Table", slug: "tm-location-table", url: "/sap-tm/foundation/advance/tm-location-table" },
      { name: "Transp. Lane Table", slug: "transportation-lane-table", url: "/sap-tm/foundation/advance/transportation-lane-table" }
    ]
  },
];

export const ORDER_MANAGEMENT_MENU = [
  {
    group: "Order Management (Basics)",
    category: "basic",
    items: [
      { name: "OTR vs DTR", slug: "otr-vs-dtr", url: "/sap-tm/order-management/basic/otr-vs-dtr" },
      { name: "Embedded TM OTRs", slug: "embedded-otr-mandatory", url: "/sap-tm/order-management/basic/embedded-otr-mandatory" },
      { name: "Freight Unit (FU)", slug: "freight-unit-definition", url: "/sap-tm/order-management/basic/freight-unit-definition" },
      { name: "Transp. Request (TR)", slug: "transportation-request-definition", url: "/sap-tm/order-management/basic/transportation-request-definition" },
      { name: "FU Transaction Code", slug: "fu-transaction-code", url: "/sap-tm/order-management/basic/fu-transaction-code" },
      { name: "Forwarding Order (FWO)", slug: "forwarding-order-definition", url: "/sap-tm/order-management/basic/forwarding-order-definition" },
      { name: "FWO vs OTR", slug: "fwo-vs-otr", url: "/sap-tm/order-management/basic/fwo-vs-otr" },
      { name: "TM Document Flow", slug: "tm-document-flow", url: "/sap-tm/order-management/basic/tm-document-flow" },
      { name: "FUB Rule (FUBR)", slug: "fubr-definition", url: "/sap-tm/order-management/basic/fubr-definition" },
      { name: "FU Source Location", slug: "fu-source-location", url: "/sap-tm/order-management/basic/fu-source-location" },
      { name: "FU Dest. Location", slug: "fu-destination-location", url: "/sap-tm/order-management/basic/fu-destination-location" },
      { name: "Freight Unit Stage", slug: "freight-unit-stage", url: "/sap-tm/order-management/basic/freight-unit-stage" },
      { name: "Incoterms in TM", slug: "incoterms-tm-relevance", url: "/sap-tm/order-management/basic/incoterms-tm-relevance" },
      { name: "FU General Data", slug: "fu-general-data-tab", url: "/sap-tm/order-management/basic/fu-general-data-tab" },
      { name: "FU Quantity", slug: "freight-unit-quantity", url: "/sap-tm/order-management/basic/freight-unit-quantity" },
      { name: "Gross vs Net Weight", slug: "gross-vs-net-weight", url: "/sap-tm/order-management/basic/gross-vs-net-weight" },
      { name: "Document Types", slug: "tm-document-types", url: "/sap-tm/order-management/basic/tm-document-types" },
      { name: "Ordering Party", slug: "ordering-party-definition", url: "/sap-tm/order-management/basic/ordering-party-definition" },
      { name: "Shipper Field", slug: "shipper-field-definition", url: "/sap-tm/order-management/basic/shipper-field-definition" },
      { name: "Consignee Field", slug: "consignee-field-definition", url: "/sap-tm/order-management/basic/consignee-field-definition" },
      { name: "Main Carriage", slug: "main-carriage-definition", url: "/sap-tm/order-management/basic/main-carriage-definition" },
      { name: "Pre-Carriage", slug: "pre-carriage-definition", url: "/sap-tm/order-management/basic/pre-carriage-definition" },
      { name: "On-Carriage", slug: "on-carriage-definition", url: "/sap-tm/order-management/basic/on-carriage-definition" },
      { name: "FU Notes", slug: "freight-unit-notes", url: "/sap-tm/order-management/basic/freight-unit-notes" },
      { name: "Requested Del. Date", slug: "requested-delivery-date", url: "/sap-tm/order-management/basic/requested-delivery-date" },
      { name: "Acceptable Del. Date", slug: "acceptable-delivery-date", url: "/sap-tm/order-management/basic/acceptable-delivery-date" },
      { name: "Freight Unit Status", slug: "freight-unit-status", url: "/sap-tm/order-management/moderate/freight-unit-status" },
      { name: "Standalone FU", slug: "standalone-freight-unit", url: "/sap-tm/order-management/moderate/standalone-freight-unit" },
      { name: "Text Schema Logic", slug: "text-schema-order-management", url: "/sap-tm/order-management/moderate/text-schema-order-management" },
      { name: "FWO Credit Check", slug: "credit-limit-check-fwo", url: "/sap-tm/order-management/moderate/credit-limit-check-fwo" },
      { name: "DG Check Order", slug: "dangerous-goods-check-order", url: "/sap-tm/order-management/moderate/dangerous-goods-check-order" },
      { name: "Trade Compliance", slug: "trade-compliance-order", url: "/sap-tm/order-management/moderate/trade-compliance-order" },
      { name: "Service Product", slug: "service-product-fwo", url: "/sap-tm/order-management/moderate/service-product-fwo" },
      { name: "FU Reference Doc", slug: "freight-unit-reference-document", url: "/sap-tm/order-management/moderate/freight-unit-reference-document" },
      { name: "Manual FU Changes", slug: "manual-fu-modification", url: "/sap-tm/order-management/moderate/manual-fu-modification" },
      { name: "SO Quantity Update", slug: "so-quantity-change-impact", url: "/sap-tm/order-management/moderate/so-quantity-change-impact" },
      { name: "Blocking Logic", slug: "order-management-blocking", url: "/sap-tm/order-management/moderate/order-management-blocking" },
      { name: "Transp. Group", slug: "transportation-group-material", url: "/sap-tm/order-management/moderate/transportation-group-material" },
      { name: "Shipping Condition", slug: "shipping-condition-definition", url: "/sap-tm/order-management/moderate/shipping-condition-definition" },
      { name: "FUBR Determination", slug: "fubr-determination-logic", url: "/sap-tm/order-management/advanced/fubr-determination-logic" }
    ]
  },
  {
    group: "Order Management (Moderate)",
    category: "moderate",
    items: [
      { name: "Map SO to TM Types", slug: "map-so-type-tm-type", url: "/sap-tm/order-management/moderate/map-so-type-tm-type" },
      { name: "LogInt Control Key", slug: "control-key-logint", url: "/sap-tm/order-management/moderate/control-key-logint" },
      { name: "Default Route Setup", slug: "default-route-setup", url: "/sap-tm/order-management/moderate/default-route-setup" },
      { name: "Credit Check Block", slug: "credit-check-block-config", url: "/sap-tm/order-management/moderate/credit-check-block-config" },
      { name: "Map Partner Functions", slug: "map-partner-functions", url: "/sap-tm/order-management/moderate/map-partner-functions" },
      { name: "FWO Text Types", slug: "fwo-text-types", url: "/sap-tm/order-management/moderate/fwo-text-types" },
      { name: "FWO Item Types", slug: "fwo-item-types", url: "/sap-tm/order-management/moderate/fwo-item-types" },
      { name: "FWO Number Ranges", slug: "fwo-number-ranges", url: "/sap-tm/order-management/moderate/fwo-number-ranges" },
      { name: "DG Profile Config", slug: "dangerous-goods-profile", url: "/sap-tm/order-management/moderate/dangerous-goods-profile" },
      { name: "Date Types Config", slug: "date-types-configuration", url: "/sap-tm/order-management/moderate/date-types-configuration" },
      { name: "Date Tolerances", slug: "date-tolerances-setup", url: "/sap-tm/order-management/moderate/date-tolerances-setup" },
      { name: "Quantity Tolerances", slug: "quantity-tolerances-setup", url: "/sap-tm/order-management/moderate/quantity-tolerances-setup" },
      { name: "HBL Numbering", slug: "hbl-numbering-config", url: "/sap-tm/order-management/moderate/hbl-numbering-config" },
      { name: "Org Interaction Status", slug: "org-interaction-status", url: "/sap-tm/order-management/moderate/org-interaction-status" },
      { name: "FSD from FWO", slug: "fsd-creation-fwo", url: "/sap-tm/order-management/moderate/fsd-creation-fwo" },
      { name: "Link FWA to FWO", slug: "link-fwa-to-fwo", url: "/sap-tm/order-management/moderate/link-fwa-to-fwo" },
      { name: "Auto Charge Calc", slug: "auto-charge-calculation", url: "/sap-tm/order-management/moderate/auto-charge-calculation" },
      { name: "FWO Templates", slug: "fwo-creation-templates", url: "/sap-tm/order-management/moderate/fwo-creation-templates" },
      { name: "Planning Block", slug: "planning-block-trigger", url: "/sap-tm/order-management/moderate/planning-block-trigger" },
      { name: "FUBR Split Quantity", slug: "fubr-split-quantity", url: "/sap-tm/order-management/advanced/fubr-split-quantity" },
      { name: "FUBR Consolidation", slug: "fubr-consolidation-logic", url: "/sap-tm/order-management/advanced/fubr-consolidation-logic" },
      { name: "Incompatibility Settings", slug: "incompatibility-settings-fu", url: "/sap-tm/order-management/advanced/incompatibility-settings-fu" },
      { name: "FUBR Condition", slug: "fubr-determination-condition", url: "/sap-tm/order-management/advanced/fubr-determination-condition" },
      { name: "Stage Building Logic", slug: "stage-building-logic", url: "/sap-tm/order-management/advanced/stage-building-logic" },
      { name: "Standard vs Linear", slug: "standard-vs-linear-stages", url: "/sap-tm/order-management/advanced/standard-vs-linear-stages" },
      { name: "Allocation Logic", slug: "allocation-order-logic", url: "/sap-tm/order-management/advanced/allocation-order-logic" },
      { name: "Process Controller", slug: "process-controller-strategy", url: "/sap-tm/order-management/advanced/process-controller-strategy" },
      { name: "Critical Quantities", slug: "fubr-critical-quantities", url: "/sap-tm/order-management/advanced/fubr-critical-quantities" },
      { name: "Change Controller", slug: "change-controller-logic", url: "/sap-tm/order-management/advanced/change-controller-logic" },
      { name: "BRFplus FUBR", slug: "brfplus-fubr-determination", url: "/sap-tm/order-management/advanced/brfplus-fubr-determination" },
      { name: "Allocation Consumption", slug: "allocation-consumption-logic", url: "/sap-tm/order-management/advanced/allocation-consumption-logic" },
      { name: "Hide FWO Tabs", slug: "hide-fwo-ui-tabs", url: "/sap-tm/order-management/advanced/hide-fwo-ui-tabs" },
      { name: "Field Status Group", slug: "field-status-group-order", url: "/sap-tm/order-management/advanced/field-status-group-order" },
      { name: "Custom FWO Statuses", slug: "custom-fwo-statuses", url: "/sap-tm/order-management/advanced/custom-fwo-statuses" },
      { name: "Profitability Analysis", slug: "profitability-analysis-fwo", url: "/sap-tm/order-management/advanced/profitability-analysis-fwo" }
    ]
  },
  {
    group: "Order Management (Advanced)",
    category: "advance",
    items: [
      { name: "Troubleshoot FU Logs", slug: "troubleshoot-fu-creation-logs", url: "/sap-tm/order-management/moderate/troubleshoot-fu-creation-logs" },
      { name: "Direct Integration (No OTR)", slug: "otr-skip-logic-embedded", url: "/sap-tm/order-management/moderate/otr-skip-logic-embedded" },
      { name: "Missing Source Loc", slug: "source-location-missing-troubleshoot", url: "/sap-tm/order-management/moderate/source-location-missing-troubleshoot" },
      { name: "Movement Type Logic", slug: "movement-type-determination-logic", url: "/sap-tm/order-management/moderate/movement-type-determination-logic" },
      { name: "BOPF Node Item Data", slug: "bopf-node-item-tr", url: "/sap-tm/order-management/moderate/bopf-node-item-tr" },
      { name: "Route Det. vs Stages", slug: "route-determination-so-tm-stages", url: "/sap-tm/order-management/moderate/route-determination-so-tm-stages" },
      { name: "Returns Order Flow", slug: "returns-order-sto-data-flow", url: "/sap-tm/order-management/moderate/returns-order-sto-data-flow" },
      { name: "FU Deletion Logic", slug: "fu-deletion-logic-cancellation", url: "/sap-tm/order-management/advanced/fu-deletion-logic-cancellation" },
      { name: "FU Rebuilding Process", slug: "freight-unit-rebuilding-process", url: "/sap-tm/order-management/advanced/freight-unit-rebuilding-process" },
      { name: "Kit-to-Order Scenario", slug: "kit-to-order-tm", url: "/sap-tm/order-management/advanced/kit-to-order-tm" },
      { name: "Condition Based FUBR", slug: "condition-based-fubr-determination", url: "/sap-tm/order-management/advanced/condition-based-fubr-determination" },
      { name: "Multi-Compartment Logic", slug: "multi-compartment-incompatibility", url: "/sap-tm/order-management/advanced/multi-compartment-incompatibility" },
      { name: "Incoterm & Stages", slug: "incoterm-locations-stage-building", url: "/sap-tm/order-management/advanced/incoterm-locations-stage-building" },
      { name: "BAdI Custom Logic", slug: "badi-custom-logic-fubr", url: "/sap-tm/order-management/advanced/badi-custom-logic-fubr" },
      { name: "Buyer's Consolidation", slug: "buyers-consolidation-fwo", url: "/sap-tm/order-management/advanced/buyers-consolidation-fwo" },
      { name: "Complete Delivery Ind.", slug: "complete-delivery-indicator-fubr", url: "/sap-tm/order-management/advanced/complete-delivery-indicator-fubr" },
      { name: "Order Combination", slug: "order-combination-grouping-tm", url: "/sap-tm/order-management/advanced/order-combination-grouping-tm" },
      { name: "Trigger EM Events", slug: "trigger-em-event-fwo", url: "/sap-tm/order-management/advanced/trigger-em-event-fwo" },
      { name: "Dimensional Weight", slug: "dimensional-volumetric-weight-logic", url: "/sap-tm/order-management/advanced/dimensional-volumetric-weight-logic" },
      { name: "Triangulation Logic", slug: "triangulation-logic-fwo", url: "/sap-tm/order-management/advanced/triangulation-logic-fwo" },
      { name: "GATP Interaction", slug: "gatp-tm-interaction", url: "/sap-tm/order-management/advanced/gatp-tm-interaction" },
      { name: "Cross-Docking", slug: "cross-docking-erp-tm", url: "/sap-tm/order-management/advanced/cross-docking-erp-tm" },
      { name: "POWL Customization", slug: "customize-powl-order-management", url: "/sap-tm/order-management/advanced/customize-powl-order-management" },
      { name: "Incoterm Change Impact", slug: "incoterm-change-impact-fu", url: "/sap-tm/order-management/advanced/incoterm-change-impact-fu" },
      { name: "System Performance", slug: "impact-small-freight-units", url: "/sap-tm/order-management/advanced/impact-small-freight-units" }
    ]
  }
]

export const PLANNING_MENU = [
  {
    group: "Planning (Basic)",
    category: "basic",
    items: [
      { name: "Transportation Cockpit", slug: "transportation-cockpit-overview", url: "/sap-tm/planning/basic/transportation-cockpit-overview" },
      { name: "Freight Order (FO)", slug: "freight-order-definition", url: "/sap-tm/planning/basic/freight-order-definition" },
      { name: "Freight Booking (FB)", slug: "freight-booking-definition", url: "/sap-tm/planning/basic/freight-booking-definition" },
      { name: "FO vs FB", slug: "fo-vs-fb-difference", url: "/sap-tm/planning/basic/fo-vs-fb-difference" },
      { name: "Cockpit Areas", slug: "cockpit-screen-areas", url: "/sap-tm/planning/basic/cockpit-screen-areas" },
      { name: "VSR Optimizer", slug: "vsr-optimizer-definition", url: "/sap-tm/planning/basic/vsr-optimizer-definition" },
      { name: "VSR Meaning", slug: "vsr-acronym-meaning", url: "/sap-tm/planning/basic/vsr-acronym-meaning" },
      { name: "Manual Planning", slug: "manual-planning-overview", url: "/sap-tm/planning/basic/manual-planning-overview" },
      { name: "Planning Profile", slug: "planning-profile-definition", url: "/sap-tm/planning/basic/planning-profile-definition" },
      { name: "Selection Profile", slug: "selection-profile-definition", url: "/sap-tm/planning/basic/selection-profile-definition" },
      { name: "Gantt Chart", slug: "gantt-chart-tm", url: "/sap-tm/planning/moderate/gantt-chart-tm" },
      { name: "Capacity Document", slug: "capacity-document-definition", url: "/sap-tm/planning/moderate/capacity-document-definition" },
      { name: "Load Planning", slug: "load-planning-definition", url: "/sap-tm/planning/moderate/load-planning-definition" },
      { name: "VSR vs Load Planning", slug: "vsr-vs-load-planning", url: "/sap-tm/planning/moderate/vsr-vs-load-planning" },
      { name: "Transp. Proposal", slug: "transportation-proposal", url: "/sap-tm/planning/moderate/transportation-proposal" },
      { name: "Optimizer Explanation", slug: "optimizer-explanation-tool", url: "/sap-tm/planning/moderate/optimizer-explanation-tool" },
      { name: "Carrier Selection", slug: "carrier-selection-overview", url: "/sap-tm/planning/moderate/carrier-selection-overview" },
      { name: "Tendering", slug: "tendering-overview", url: "/sap-tm/planning/moderate/tendering-overview" },
      { name: "Planning Horizon", slug: "planning-horizon-definition", url: "/sap-tm/planning/moderate/planning-horizon-definition" },
      { name: "Decreasing Capacity", slug: "decreasing-capacity-resources", url: "/sap-tm/planning/moderate/decreasing-capacity-resources" },
      { name: "Scheduling", slug: "scheduling-definition", url: "/sap-tm/planning/moderate/scheduling-definition" },
      { name: "Fwd vs Bwd Scheduling", slug: "forward-vs-backward-scheduling", url: "/sap-tm/planning/moderate/forward-vs-backward-scheduling" },
      { name: "Hard Constraint", slug: "hard-constraint-definition", url: "/sap-tm/planning/moderate/hard-constraint-definition" },
      { name: "Soft Constraint", slug: "soft-constraint-definition", url: "/sap-tm/planning/moderate/soft-constraint-definition" },
      { name: "Penalty Cost", slug: "penalty-cost-definition", url: "/sap-tm/planning/moderate/penalty-cost-definition" },
      { name: "Cockpit Trips", slug: "cockpit-trips-view", url: "/sap-tm/planning/advanced/cockpit-trips-view" },
      { name: "Cockpit Map View", slug: "cockpit-map-view", url: "/sap-tm/planning/advanced/cockpit-map-view" },
      { name: "Context Menu", slug: "context-menu-planning", url: "/sap-tm/planning/advanced/context-menu-planning" },
      { name: "Drag and Drop", slug: "drag-and-drop-planning", url: "/sap-tm/planning/advanced/drag-and-drop-planning" },
      { name: "Planning Strategy", slug: "planning-strategy-definition", url: "/sap-tm/planning/advanced/planning-strategy-definition" },
      { name: "Optimizer Runtime", slug: "optimizer-runtime-config", url: "/sap-tm/planning/advanced/optimizer-runtime-config" },
      { name: "Load Consolidation", slug: "load-consolidation-logic", url: "/sap-tm/planning/advanced/load-consolidation-logic" },
      { name: "Multi-Drop", slug: "multi-drop-routing", url: "/sap-tm/planning/advanced/multi-drop-routing" },
      { name: "Multi-Pick", slug: "multi-pick-routing", url: "/sap-tm/planning/advanced/multi-pick-routing" },
      { name: "Continuous Move", slug: "continuous-move-planning", url: "/sap-tm/planning/advanced/continuous-move-planning" },
      { name: "Schedules", slug: "schedules-in-planning", url: "/sap-tm/planning/advanced/schedules-in-planning" },
      { name: "Departure Calendar", slug: "departure-calendar-usage", url: "/sap-tm/planning/advanced/departure-calendar-usage" },
      { name: "Receiving Calendar", slug: "receiving-calendar-usage", url: "/sap-tm/planning/advanced/receiving-calendar-usage" },
      { name: "Fixing FO", slug: "fixing-freight-order", url: "/sap-tm/planning/advanced/fixing-freight-order" },
      { name: "Unplanning Process", slug: "unplanning-process", url: "/sap-tm/planning/advanced/unplanning-process" }
    ]
  },
  {
    group: "Planning (Moderate)",
    category: "moderate",
    items: [
      { name: "Config Planning Profile", slug: "configure-planning-profile", url: "/sap-tm/planning/configuration/configure-planning-profile" },
      { name: "Link Profile to User", slug: "link-planning-profile-user", url: "/sap-tm/planning/configuration/link-planning-profile-user" },
      { name: "Optimizer Settings", slug: "optimizer-settings-profile", url: "/sap-tm/planning/configuration/optimizer-settings-profile" },
      { name: "Capacity Selection", slug: "capacity-selection-settings", url: "/sap-tm/planning/configuration/capacity-selection-settings" },
      { name: "Time-Related Attributes", slug: "time-related-selection-attributes", url: "/sap-tm/planning/configuration/time-related-selection-attributes" },
      { name: "Cockpit Page Layout", slug: "cockpit-page-layout-config", url: "/sap-tm/planning/configuration/cockpit-page-layout-config" },
      { name: "Cockpit Hierarchy", slug: "cockpit-hierarchy-creation", url: "/sap-tm/planning/configuration/cockpit-hierarchy-creation" },
      { name: "Cap. Doc. Creation", slug: "capacity-document-creation-settings", url: "/sap-tm/planning/configuration/capacity-document-creation-settings" },
      { name: "Scheduling Settings", slug: "scheduling-settings-config", url: "/sap-tm/planning/configuration/scheduling-settings-config" },
      { name: "Carrier Sel. Settings", slug: "carrier-selection-settings-config", url: "/sap-tm/planning/configuration/carrier-selection-settings-config" },
      { name: "Optimization vs Check", slug: "optimization-vs-check-diff", url: "/sap-tm/planning/configuration/optimization-vs-check-diff" },
      { name: "Planning Incompatibilities", slug: "planning-incompatibilities-config", url: "/sap-tm/planning/configuration/planning-incompatibilities-config" },
      { name: "Cockpit Filter Conditions", slug: "cockpit-filter-conditions", url: "/sap-tm/planning/configuration/cockpit-filter-conditions" },
      { name: "Map Integration Setup", slug: "map-integration-cockpit", url: "/sap-tm/planning/configuration/map-integration-cockpit" },
      { name: "Gantt Chart Colors", slug: "gantt-chart-color-config", url: "/sap-tm/planning/configuration/gantt-chart-color-config" },
      { name: "Manual Planning Config", slug: "manual-planning-settings-config", url: "/sap-tm/planning/configuration/manual-planning-settings-config" },
      { name: "Enable Undo/Redo", slug: "enable-undo-redo-cockpit", url: "/sap-tm/planning/configuration/enable-undo-redo-cockpit" },
      { name: "Field Status Cockpit", slug: "field-status-transportation-cockpit", url: "/sap-tm/planning/configuration/field-status-transportation-cockpit" },
      { name: "Optimizer Cost Functions", slug: "optimizer-cost-functions", url: "/sap-tm/planning/strategies/optimizer-cost-functions" },
      { name: "Penalty Costs Config", slug: "penalty-costs-earliness-lateness", url: "/sap-tm/planning/strategies/penalty-costs-earliness-lateness" },
      { name: "TSPS Strategy", slug: "planning-strategy-tsps", url: "/sap-tm/planning/strategies/planning-strategy-tsps" },
      { name: "Load Planning Settings", slug: "load-planning-settings-config", url: "/sap-tm/planning/strategies/load-planning-settings-config" },
      { name: "Stackability Config", slug: "stackability-configuration", url: "/sap-tm/planning/strategies/stackability-configuration" },
      { name: "Tendering Profiles", slug: "tendering-profiles-setup", url: "/sap-tm/planning/strategies/tendering-profiles-setup" },
      { name: "Peer-to-Peer Tendering", slug: "peer-to-peer-tendering-config", url: "/sap-tm/planning/strategies/peer-to-peer-tendering-config" },
      { name: "Broadcast Tendering", slug: "broadcast-tendering-config", url: "/sap-tm/planning/strategies/broadcast-tendering-config" },
      { name: "Tendering Review Step", slug: "tendering-review-step", url: "/sap-tm/planning/strategies/tendering-review-step" },
      { name: "Decreasing Caps Model", slug: "decreasing-capacities-model", url: "/sap-tm/planning/strategies/decreasing-capacities-model" },
      { name: "Driver Visibility", slug: "driver-visibility-cockpit", url: "/sap-tm/planning/strategies/driver-visibility-cockpit" },
      { name: "Default Routes Opt.", slug: "default-routes-optimizer", url: "/sap-tm/planning/strategies/default-routes-optimizer" },
      { name: "Equipment Types Logic", slug: "equipment-types-consideration", url: "/sap-tm/planning/strategies/equipment-types-consideration" },
      { name: "Plan vs Actual Costs", slug: "planning-vs-actual-costs", url: "/sap-tm/planning/strategies/planning-vs-actual-costs" },
      { name: "Time Windows Config", slug: "time-windows-hard-soft", url: "/sap-tm/planning/strategies/time-windows-hard-soft" },
      { name: "Driver Breaks Setup", slug: "driver-breaks-rest-periods", url: "/sap-tm/planning/strategies/driver-breaks-rest-periods" },
      { name: "Lane Validity Periods", slug: "lane-validity-periods-planning", url: "/sap-tm/planning/strategies/lane-validity-periods-planning" }
    ]
  },
  {
    group: "Planning (Advance)",
    category: "advance",
    items: [
      { name: "Unplanned FUs Debug", slug: "optimizer-unplanned-fus-debug", url: "/sap-tm/planning/troubleshooting/optimizer-unplanned-fus-debug" },
      { name: "VSR Algorithm Logic", slug: "vsr-optimization-algorithm-logic", url: "/sap-tm/planning/troubleshooting/vsr-optimization-algorithm-logic" },
      { name: "RCC_LOG Debugging", slug: "rcc-log-optimizer-debug", url: "/sap-tm/planning/troubleshooting/rcc-log-optimizer-debug" },
      { name: "Gantt Blank Issues", slug: "gantt-chart-blank-troubleshoot", url: "/sap-tm/planning/troubleshooting/gantt-chart-blank-troubleshoot" },
      { name: "Infeasible Results", slug: "optimizer-infeasible-results-fix", url: "/sap-tm/planning/troubleshooting/optimizer-infeasible-results-fix" },
      { name: "Performance: Horizon", slug: "planning-horizon-performance-impact", url: "/sap-tm/planning/troubleshooting/planning-horizon-performance-impact" },
      { name: "Performance: FU Limit", slug: "optimizer-fu-limit-recommendation", url: "/sap-tm/planning/troubleshooting/optimizer-fu-limit-recommendation" },
      { name: "Parallel Processing", slug: "optimizer-parallel-processing-setup", url: "/sap-tm/planning/troubleshooting/optimizer-parallel-processing-setup" },
      { name: "Travel Time (No GIS)", slug: "travel-time-calculation-no-gis", url: "/sap-tm/planning/troubleshooting/travel-time-calculation-no-gis" },
      { name: "Driver vs Vehicle Hours", slug: "driver-hours-vs-vehicle-availability", url: "/sap-tm/planning/troubleshooting/driver-hours-vs-vehicle-availability" },
      { name: "Cost Priority Setup", slug: "optimizer-cost-priority-setup", url: "/sap-tm/planning/scenarios/optimizer-cost-priority-setup" },
      { name: "Hub-and-Spoke Setup", slug: "hub-and-spoke-optimizer-model", url: "/sap-tm/planning/scenarios/hub-and-spoke-optimizer-model" },
      { name: "3D Load Planning", slug: "3d-load-planning-configuration", url: "/sap-tm/planning/scenarios/3d-load-planning-configuration" },
      { name: "Trailer Swaps", slug: "trailer-swap-drop-hook-planning", url: "/sap-tm/planning/scenarios/trailer-swap-drop-hook-planning" },
      { name: "Incremental vs Regen", slug: "incremental-vs-regenerative-planning", url: "/sap-tm/planning/scenarios/incremental-vs-regenerative-planning" },
      { name: "Target Allocation", slug: "carrier-target-allocation-optimizer", url: "/sap-tm/planning/scenarios/carrier-target-allocation-optimizer" },
      { name: "PP Integration Impact", slug: "production-planning-integration-tm", url: "/sap-tm/planning/scenarios/production-planning-integration-tm" },
      { name: "Multi-Compartment Plan", slug: "multi-compartment-truck-planning", url: "/sap-tm/planning/scenarios/multi-compartment-truck-planning" },
      { name: "Auto Planning Jobs", slug: "automatic-planning-batch-jobs", url: "/sap-tm/planning/scenarios/automatic-planning-batch-jobs" },
      { name: "Milk Run Config", slug: "milk-run-optimizer-configuration", url: "/sap-tm/planning/scenarios/milk-run-optimizer-configuration" },
      { name: "Cockpit Scripts", slug: "transportation-cockpit-scripts", url: "/sap-tm/planning/scenarios/transportation-cockpit-scripts" },
      { name: "Rush Orders Logic", slug: "rush-order-planning-disruption", url: "/sap-tm/planning/scenarios/rush-order-planning-disruption" },
      { name: "Railcar Aggregation", slug: "railcar-aggregation-planning", url: "/sap-tm/planning/scenarios/railcar-aggregation-planning" },
      { name: "Strategic Procurement", slug: "strategic-freight-procurement-planning", url: "/sap-tm/planning/scenarios/strategic-freight-procurement-planning" },
      { name: "Cross-Docking Logic", slug: "cross-docking-planning-logic", url: "/sap-tm/planning/scenarios/cross-docking-planning-logic" }
    ]
  },
]


export const CHARGE_MENU = [
  {
    group: "Charges & Settlement (Basic)",
    category: "basic",
    items: [
      { name: "Charge Management", slug: "charge-management-overview", url: "/sap-tm/charge-management/basic/charge-management-overview" },
      { name: "Freight Settlement (FSD)", slug: "freight-settlement-document", url: "/sap-tm/charge-management/basic/freight-settlement-document" },
      { name: "Fwd. Settlement (FWSD)", slug: "forwarding-settlement-document", url: "/sap-tm/charge-management/basic/forwarding-settlement-document" },
      { name: "FSD vs FWSD", slug: "fsd-vs-fwsd-difference", url: "/sap-tm/charge-management/basic/fsd-vs-fwsd-difference" },
      { name: "Calc. Sheet (TCCS)", slug: "tccs-definition", url: "/sap-tm/charge-management/basic/tccs-definition" },
      { name: "Rate Table", slug: "rate-table-definition", url: "/sap-tm/charge-management/basic/rate-table-definition" },
      { name: "Scale Definition", slug: "scale-definition", url: "/sap-tm/charge-management/basic/scale-definition" },
      { name: "Calculation Base", slug: "calculation-base-definition", url: "/sap-tm/charge-management/basic/calculation-base-definition" },
      { name: "Charge Type", slug: "charge-type-definition", url: "/sap-tm/charge-management/basic/charge-type-definition" },
      { name: "Std vs Accessorial", slug: "standard-vs-accessorial-charge", url: "/sap-tm/charge-management/basic/standard-vs-accessorial-charge" },
      { name: "Fuel Surcharge", slug: "fuel-surcharge-definition", url: "/sap-tm/charge-management/basic/fuel-surcharge-definition" },
      { name: "Dimensional Weight", slug: "dimensional-weight-charges", url: "/sap-tm/charge-management/basic/dimensional-weight-charges" },
      { name: "Resolution Base", slug: "resolution-base-definition", url: "/sap-tm/charge-management/basic/resolution-base-definition" },
      { name: "Cost Distribution", slug: "cost-distribution-logic", url: "/sap-tm/charge-management/moderate/cost-distribution-logic" },
      { name: "Account Determination", slug: "account-determination-setup", url: "/sap-tm/charge-management/moderate/account-determination-setup" },
      { name: "Service PO Integration", slug: "service-purchase-order-integration", url: "/sap-tm/charge-management/moderate/service-purchase-order-integration" },
      { name: "Service Entry Sheet", slug: "service-entry-sheet-creation", url: "/sap-tm/charge-management/moderate/service-entry-sheet-creation" },
      { name: "Agency Business (ABD)", slug: "agency-business-document-settlement", url: "/sap-tm/charge-management/moderate/agency-business-document-settlement" },
      { name: "Invoice Verification", slug: "invoice-verification-process", url: "/sap-tm/charge-management/moderate/invoice-verification-process" },
      { name: "Credit Memo", slug: "credit-memo-process", url: "/sap-tm/charge-management/moderate/credit-memo-process" },
      { name: "Dispute Management", slug: "dispute-case-management", url: "/sap-tm/charge-management/moderate/dispute-case-management" },
      { name: "Self-Billing", slug: "self-billing-process", url: "/sap-tm/charge-management/moderate/self-billing-process" },
      { name: "Freight Agreement", slug: "freight-agreement-definition", url: "/sap-tm/charge-management/moderate/freight-agreement-definition" },
      { name: "Forwarding Agreement", slug: "forwarding-agreement-definition", url: "/sap-tm/charge-management/moderate/forwarding-agreement-definition" },
      { name: "Agreement Pre-condition", slug: "agreement-pre-condition", url: "/sap-tm/charge-management/moderate/agreement-pre-condition" },
      { name: "Calculation Date", slug: "calculation-date-logic", url: "/sap-tm/charge-management/moderate/calculation-date-logic" },
      { name: "Currency Conversion", slug: "currency-conversion-tm", url: "/sap-tm/charge-management/advanced/currency-conversion-tm" },
      { name: "Tax Determination", slug: "tax-determination-tm", url: "/sap-tm/charge-management/advanced/tax-determination-tm" },
      { name: "Charge Element", slug: "charge-element-definition", url: "/sap-tm/charge-management/advanced/charge-element-definition" },
      { name: "TCCS Grouping", slug: "tccs-grouping-logic", url: "/sap-tm/charge-management/advanced/tccs-grouping-logic" },
      { name: "Minimum Charge", slug: "minimum-charge-calculation", url: "/sap-tm/charge-management/advanced/minimum-charge-calculation" },
      { name: "Through Rate", slug: "through-rate-definition", url: "/sap-tm/charge-management/advanced/through-rate-definition" },
      { name: "Break-Weight", slug: "break-weight-calculation", url: "/sap-tm/charge-management/advanced/break-weight-calculation" },
      { name: "Internal Settlement", slug: "internal-settlement-overview", url: "/sap-tm/charge-management/advanced/internal-settlement-overview" },
      { name: "Profitability Analysis", slug: "profitability-analysis-tm", url: "/sap-tm/charge-management/advanced/profitability-analysis-tm" },
      { name: "Cost Pull vs Push", slug: "cost-pull-vs-push-logic", url: "/sap-tm/charge-management/advanced/cost-pull-vs-push-logic" },
      { name: "Charges Tab (FO)", slug: "charges-tab-freight-order", url: "/sap-tm/charge-management/advanced/charges-tab-freight-order" },
      { name: "Charge Hierarchy", slug: "charge-hierarchy-logic", url: "/sap-tm/charge-management/advanced/charge-hierarchy-logic" },
      { name: "Leading Charge Type", slug: "leading-charge-type", url: "/sap-tm/charge-management/advanced/leading-charge-type" },
      { name: "Local vs Global Rates", slug: "local-vs-global-rate-table", url: "/sap-tm/charge-management/advanced/local-vs-global-rate-table" }
    ]
  },
  {
    group: "Charges & Settlement (Moderate)",
    category: "moderate",
    items: [
      { name: "Create Weight Scale", slug: "create-scale-weight", url: "/sap-tm/charge-management/rates-calculation/create-scale-weight" },
      { name: "2D Rate Table Config", slug: "rate-table-2d-config", url: "/sap-tm/charge-management/rates-calculation/rate-table-2d-config" },
      { name: "Link Rate Table to TCCS", slug: "link-rate-table-tccs", url: "/sap-tm/charge-management/rates-calculation/link-rate-table-tccs" },
      { name: "Calculation Methods", slug: "calculation-method-config", url: "/sap-tm/charge-management/rates-calculation/calculation-method-config" },
      { name: "Condition Types Charges", slug: "condition-types-charges", url: "/sap-tm/charge-management/rates-calculation/condition-types-charges" },
      { name: "Agreement Types", slug: "agreement-types-config", url: "/sap-tm/charge-management/rates-calculation/agreement-types-config" },
      { name: "Charge Profiles", slug: "charge-profiles-config", url: "/sap-tm/charge-management/rates-calculation/charge-profiles-config" },
      { name: "Rate Table Template", slug: "rate-table-template", url: "/sap-tm/charge-management/rates-calculation/rate-table-template" },
      { name: "Index Rates (Fuel)", slug: "index-rates-fuel", url: "/sap-tm/charge-management/rates-calculation/index-rates-fuel" },
      { name: "Postal Code Scales", slug: "postal-code-scales", url: "/sap-tm/charge-management/rates-calculation/postal-code-scales" },
      { name: "Calc. Resolution Logic", slug: "calculation-resolution-logic", url: "/sap-tm/charge-management/rates-calculation/calculation-resolution-logic" },
      { name: "Min/Max Charge Values", slug: "min-max-charge-values", url: "/sap-tm/charge-management/rates-calculation/min-max-charge-values" },
      { name: "Charge Calc Logic", slug: "charge-calc-logic-badi", url: "/sap-tm/charge-management/rates-calculation/charge-calc-logic-badi" },
      { name: "Link BP to Agreements", slug: "link-bp-agreements", url: "/sap-tm/charge-management/rates-calculation/link-bp-agreements" },
      { name: "Rate Validity Periods", slug: "rate-validity-periods", url: "/sap-tm/charge-management/rates-calculation/rate-validity-periods" },
      { name: "Releasing Agreements", slug: "releasing-agreements-setup", url: "/sap-tm/charge-management/rates-calculation/releasing-agreements-setup" },
      { name: "Manual Charge Lines", slug: "manual-charge-lines-setup", url: "/sap-tm/charge-management/rates-calculation/manual-charge-lines-setup" },
      { name: "Percentage Charges", slug: "percentage-based-charges", url: "/sap-tm/charge-management/rates-calculation/percentage-based-charges" },
      { name: "Absolute Charges", slug: "absolute-charges-setup", url: "/sap-tm/charge-management/rates-calculation/absolute-charges-setup" },
      { name: "Tiered vs Flat Rates", slug: "tiered-vs-flat-rates", url: "/sap-tm/charge-management/rates-calculation/tiered-vs-flat-rates" },
      { name: "Commodity Codes", slug: "commodity-codes-rating", url: "/sap-tm/charge-management/rates-calculation/commodity-codes-rating" },
      { name: "Service Level Impact", slug: "service-level-rate-impact", url: "/sap-tm/charge-management/rates-calculation/service-level-rate-impact" },
      { name: "Incoterms Impact", slug: "incoterms-impact-charges", url: "/sap-tm/charge-management/rates-calculation/incoterms-impact-charges" },
      { name: "Cost Dist. Profiles", slug: "cost-distribution-profile", url: "/sap-tm/charge-management/settlement-integration/cost-distribution-profile" },
      { name: "Map to Service Master", slug: "map-charge-service-master", url: "/sap-tm/charge-management/settlement-integration/map-charge-service-master" },
      { name: "Map to G/L Accounts", slug: "map-charge-gl-account", url: "/sap-tm/charge-management/settlement-integration/map-charge-gl-account" },
      { name: "Org Unit Mapping", slug: "org-unit-mapping-settlement", url: "/sap-tm/charge-management/settlement-integration/org-unit-mapping-settlement" },
      { name: "Settlement Profile", slug: "settlement-profile-config", url: "/sap-tm/charge-management/settlement-integration/settlement-profile-config" },
      { name: "Instruction Types", slug: "settlement-instruction-types", url: "/sap-tm/charge-management/settlement-integration/settlement-instruction-types" },
      { name: "Exchange Rate Types", slug: "exchange-rate-types-config", url: "/sap-tm/charge-management/settlement-integration/exchange-rate-types-config" },
      { name: "Tolerance Groups", slug: "tolerance-groups-disputes", url: "/sap-tm/charge-management/settlement-integration/tolerance-groups-disputes" },
      { name: "Copy Control (Charges)", slug: "copy-control-charges-fo-fsd", url: "/sap-tm/charge-management/settlement-integration/copy-control-charges-fo-fsd" },
      { name: "Tax Codes Mapping", slug: "tax-codes-mapping-config", url: "/sap-tm/charge-management/settlement-integration/tax-codes-mapping-config" },
      { name: "Settlement Doc Types", slug: "settlement-document-types", url: "/sap-tm/charge-management/settlement-integration/settlement-document-types" },
      { name: "Collective Settlement", slug: "collective-settlement-config", url: "/sap-tm/charge-management/settlement-integration/collective-settlement-config" }
    ]
  },
  {
    group: "Charges & Settlement (Advance)",
    category: "advance",
    items: [
      { name: "Pallet Spaces Rating", slug: "pallet-spaces-rating-config", url: "/sap-tm/charge-management/scenarios-troubleshooting/pallet-spaces-rating-config" },
      { name: "Unplanned Accessorials", slug: "unplanned-accessorials-execution", url: "/sap-tm/charge-management/scenarios-troubleshooting/unplanned-accessorials-execution" },
      { name: "TCCS Determination", slug: "tccs-determination-logic", url: "/sap-tm/charge-management/scenarios-troubleshooting/tccs-determination-logic" },
      { name: "Carrier Dispute Workflow", slug: "carrier-dispute-workflow", url: "/sap-tm/charge-management/scenarios-troubleshooting/carrier-dispute-workflow" },
      { name: "Deficit Weight Rating", slug: "deficit-weight-rating-logic", url: "/sap-tm/charge-management/scenarios-troubleshooting/deficit-weight-rating-logic" },
      { name: "Dim. Weight Logic", slug: "dimensional-weight-calculation-logic", url: "/sap-tm/charge-management/scenarios-troubleshooting/dimensional-weight-calculation-logic" },
      { name: "Foreign Currency Settl.", slug: "foreign-currency-settlement", url: "/sap-tm/charge-management/scenarios-troubleshooting/foreign-currency-settlement" },
      { name: "Troubleshoot Calc Failures", slug: "troubleshoot-charge-calculation-failure", url: "/sap-tm/charge-management/scenarios-troubleshooting/troubleshoot-charge-calculation-failure" },
      { name: "Toll Charges Integration", slug: "toll-charges-actual-distance", url: "/sap-tm/charge-management/scenarios-troubleshooting/toll-charges-actual-distance" },
      { name: "Dynamic Fuel Surcharge", slug: "dynamic-fuel-surcharge-index", url: "/sap-tm/charge-management/scenarios-troubleshooting/dynamic-fuel-surcharge-index" },
      { name: "Rate Table Clipping", slug: "clipping-rate-tables-logic", url: "/sap-tm/charge-management/scenarios-troubleshooting/clipping-rate-tables-logic" },
      { name: "Credit Memo Process", slug: "credit-memo-overpayment-process", url: "/sap-tm/charge-management/scenarios-troubleshooting/credit-memo-overpayment-process" },
      { name: "Multi-Carrier Stage", slug: "multi-carrier-settlement-stage", url: "/sap-tm/charge-management/scenarios-troubleshooting/multi-carrier-settlement-stage" },
      { name: "Charge Levels Logic", slug: "charge-hierarchy-levels-header-stage-item", url: "/sap-tm/charge-management/scenarios-troubleshooting/charge-hierarchy-levels-header-stage-item" },
      { name: "FSD to Finance Logic", slug: "posting-logic-fsd-finance", url: "/sap-tm/charge-management/advanced-integration/posting-logic-fsd-finance" },
      { name: "Rate Table Excel Upload", slug: "rate-table-excel-integration", url: "/sap-tm/charge-management/advanced-integration/rate-table-excel-integration" },
      { name: "Cost Dist. to CO-PA", slug: "cost-distribution-copa-integration", url: "/sap-tm/charge-management/advanced-integration/cost-distribution-copa-integration" },
      { name: "Intercompany Settlement", slug: "intercompany-settlement-scenario", url: "/sap-tm/charge-management/advanced-integration/intercompany-settlement-scenario" },
      { name: "BRFplus Charge Logic", slug: "brfplus-charge-calculation", url: "/sap-tm/charge-management/advanced-integration/brfplus-charge-calculation" },
      { name: "BOPF Charge Node", slug: "bopf-node-charge-lines", url: "/sap-tm/charge-management/advanced-integration/bopf-node-charge-lines" },
      { name: "Direct Invoice (No PO)", slug: "embedded-tm-direct-invoice", url: "/sap-tm/charge-management/advanced-integration/embedded-tm-direct-invoice" },
      { name: "Calc. Performance Tuning", slug: "charge-calculation-performance-tuning", url: "/sap-tm/charge-management/advanced-integration/charge-calculation-performance-tuning" },
      { name: "SFM to Agreement", slug: "sfm-rfq-to-agreement-conversion", url: "/sap-tm/charge-management/advanced-integration/sfm-rfq-to-agreement-conversion" },
      { name: "MIRO Update to TM", slug: "miro-invoice-verification-tm-update", url: "/sap-tm/charge-management/advanced-integration/miro-invoice-verification-tm-update" },
      { name: "Archiving Best Practices", slug: "settlement-document-archiving-best-practices", url: "/sap-tm/charge-management/advanced-integration/settlement-document-archiving-best-practices" }
    ]
  }
]

export const TM_EWM = [
  {
    group: "TM-EWM Integration (Basic)",
    category: "basic",
    items: [
      { name: "Integration Types", slug: "tm-ewm-integration-types", url: "/sap-tm/tm-ewm-integration/basic/tm-ewm-integration-types" },
      { name: "ASR Definition", slug: "asr-advanced-shipping-receiving", url: "/sap-tm/tm-ewm-integration/basic/asr-advanced-shipping-receiving" },
      { name: "Transportation Unit (TU)", slug: "transportation-unit-ewm", url: "/sap-tm/tm-ewm-integration/basic/transportation-unit-ewm" },
      { name: "TU usage in ASR", slug: "tu-usage-in-asr-scenario", url: "/sap-tm/tm-ewm-integration/basic/tu-usage-in-asr-scenario" },
      { name: "Direct Integration", slug: "direct-integration-definition", url: "/sap-tm/tm-ewm-integration/basic/direct-integration-definition" },
      { name: "Order vs Delivery Int.", slug: "order-vs-delivery-based-integration", url: "/sap-tm/tm-ewm-integration/basic/order-vs-delivery-based-integration" },
      { name: "LDAP Message", slug: "ldap-loading-appointment-message", url: "/sap-tm/tm-ewm-integration/warehouse-process/ldap-loading-appointment-message" },
      { name: "Loading Point", slug: "loading-point-tm-ewm", url: "/sap-tm/tm-ewm-integration/warehouse-process/loading-point-tm-ewm" },
      { name: "Warehouse Door", slug: "warehouse-door-definition", url: "/sap-tm/tm-ewm-integration/warehouse-process/warehouse-door-definition" },
      { name: "Staging Area", slug: "staging-area-definition", url: "/sap-tm/tm-ewm-integration/warehouse-process/staging-area-definition" },
      { name: "Post Goods Issue (PGI)", slug: "pgi-post-goods-issue-tm", url: "/sap-tm/tm-ewm-integration/warehouse-process/pgi-post-goods-issue-tm" },
      { name: "Planned Arrival Time", slug: "planned-arrival-time-meaning", url: "/sap-tm/tm-ewm-integration/warehouse-process/planned-arrival-time-meaning" },
      { name: "Integration Trigger", slug: "tm-ewm-integration-trigger", url: "/sap-tm/tm-ewm-integration/technical-setup/tm-ewm-integration-trigger" },
      { name: "SHPMNT IDoc", slug: "shpmnt-idoc-legacy-vs-new", url: "/sap-tm/tm-ewm-integration/technical-setup/shpmnt-idoc-legacy-vs-new" },
      { name: "SOAP Services", slug: "soap-services-integration", url: "/sap-tm/tm-ewm-integration/technical-setup/soap-services-integration" }
    ]
  },
  {
    group: "TM-EWM Integration (Moderate)",
    category: "moderate",
    items: [
      { name: "Integration Profile", slug: "ewm-integration-profile-config", url: "/sap-tm/tm-ewm-integration/config-data/ewm-integration-profile-config" },
      { name: "Map Packaging Mat.", slug: "map-packaging-material-tm-ewm", url: "/sap-tm/tm-ewm-integration/config-data/map-packaging-material-tm-ewm" },
      { name: "Loading Instr. Trigger", slug: "loading-instruction-trigger-config", url: "/sap-tm/tm-ewm-integration/config-data/loading-instruction-trigger-config" },
      { name: "Warehouse Num. Master", slug: "warehouse-number-tm-master-data", url: "/sap-tm/tm-ewm-integration/config-data/warehouse-number-tm-master-data" },
      { name: "Batch Management", slug: "batch-management-tm-ewm", url: "/sap-tm/tm-ewm-integration/config-data/batch-management-tm-ewm" },
      { name: "Door Assignment Logic", slug: "door-assignment-logic-setup", url: "/sap-tm/tm-ewm-integration/config-data/door-assignment-logic-setup" },
      { name: "TU Status Flow", slug: "tu-status-update-flow", url: "/sap-tm/tm-ewm-integration/advanced-scenarios/tu-status-update-flow" },
      { name: "ASR EWM App View", slug: "asr-freight-order-ewm-view", url: "/sap-tm/tm-ewm-integration/advanced-scenarios/asr-freight-order-ewm-view" },
      { name: "Consignment Order ASR", slug: "consignment-order-role-asr", url: "/sap-tm/tm-ewm-integration/advanced-scenarios/consignment-order-role-asr" },
      { name: "Cross-Docking Setup", slug: "cross-docking-integration-setup", url: "/sap-tm/tm-ewm-integration/advanced-scenarios/cross-docking-integration-setup" }
    ]
  },
  {
    group: "TM-EWM Integration (Advance)",
    category: "advance",
    items: [
      { name: "Unplanned HU in ASR", slug: "unplanned-hu-asr-reaction", url: "/sap-tm/tm-ewm-integration/scenarios-troubleshooting/unplanned-hu-asr-reaction" },
      { name: "Troubleshoot LDAP Fail", slug: "ldap-failure-troubleshooting", url: "/sap-tm/tm-ewm-integration/scenarios-troubleshooting/ldap-failure-troubleshooting" },
      { name: "ASR Document Flow", slug: "asr-document-flow-architecture", url: "/sap-tm/tm-ewm-integration/scenarios-troubleshooting/asr-document-flow-architecture" },
      { name: "PGI Reversal Impact", slug: "pgi-reversal-impact-charges", url: "/sap-tm/tm-ewm-integration/scenarios-troubleshooting/pgi-reversal-impact-charges" },
      { name: "EWM Yard vs SAP YL", slug: "ewm-yard-vs-sap-yl", url: "/sap-tm/tm-ewm-integration/scenarios-troubleshooting/ewm-yard-vs-sap-yl" }
    ]
  }
]

export const TM_GTS = [
  {
    group: "TM-GTS Integration (Basics)",
    category: "basic",
    items: [
      { name: "SPL (Sanctioned Party)", slug: "spl-sanctioned-party-list", url: "/sap-tm/gts-customs/basic/spl-sanctioned-party-list" },
      { name: "Embargo Check", slug: "embargo-check-definition", url: "/sap-tm/gts-customs/basic/embargo-check-definition" },
      { name: "License Management", slug: "license-management-definition", url: "/sap-tm/gts-customs/basic/license-management-definition" },
      { name: "AES (Export System)", slug: "aes-automated-export-system", url: "/sap-tm/gts-customs/basic/aes-automated-export-system" },
      { name: "Customs Declaration", slug: "customs-declaration-definition", url: "/sap-tm/gts-customs/basic/customs-declaration-definition" },
      { name: "MRN Definition", slug: "mrn-movement-reference-number", url: "/sap-tm/gts-customs/basic/mrn-movement-reference-number" },
      { name: "Trade Compliance", slug: "trade-compliance-definition", url: "/sap-tm/gts-customs/basic/trade-compliance-definition" },
      { name: "SPL Trigger in TM", slug: "spl-check-trigger-tm", url: "/sap-tm/gts-customs/basic/spl-check-trigger-tm" },
      { name: "Blocked for Customs", slug: "blocked-for-customs-status", url: "/sap-tm/gts-customs/basic/blocked-for-customs-status" },
      { name: "HS / Commodity Code", slug: "hs-code-commodity-code", url: "/sap-tm/gts-customs/basic/hs-code-commodity-code" }
    ]
  },
  {
    group: "TM-GTS Integration (Moderate)",
    category: "moderate",
    items: [
      { name: "Activate GTS for FO", slug: "activate-gts-integration-fo-type", url: "/sap-tm/gts-customs/configuration/activate-gts-integration-fo-type" },
      { name: "Map TM-GTS Partners", slug: "map-tm-gts-business-partners", url: "/sap-tm/gts-customs/configuration/map-tm-gts-business-partners" },
      { name: "Customs Profile Config", slug: "configure-customs-profile-tm", url: "/sap-tm/gts-customs/configuration/configure-customs-profile-tm" },
      { name: "Technical Cancellation", slug: "technical-cancellation-customs-declaration", url: "/sap-tm/gts-customs/configuration/technical-cancellation-customs-declaration" },
      { name: "Map Doc Types", slug: "map-document-types-tm-gts", url: "/sap-tm/gts-customs/configuration/map-document-types-tm-gts" },
      { name: "Legal Regulations", slug: "configure-legal-regulations-gts", url: "/sap-tm/gts-customs/configuration/configure-legal-regulations-gts" },
      { name: "Bonded Warehousing", slug: "bonded-warehousing-scenarios", url: "/sap-tm/gts-customs/configuration/bonded-warehousing-scenarios" },
      { name: "GTS Fallback Setup", slug: "gts-fallback-procedure-config", url: "/sap-tm/gts-customs/configuration/gts-fallback-procedure-config" },
      { name: "Compliance vs Customs", slug: "compliance-vs-customs-management-diff", url: "/sap-tm/gts-customs/configuration/compliance-vs-customs-management-diff" },
      { name: "Blocked Order Alerts", slug: "email-alerts-blocked-orders-gts", url: "/sap-tm/gts-customs/configuration/email-alerts-blocked-orders-gts" }
    ]
  },
  {
    group: "TM-GTS Integration (Advance)",
    category: "advance",
    items: [
      { name: "Block & Unloading Ops", slug: "gts-block-unloading-procedure", url: "/sap-tm/gts-customs/scenarios-troubleshooting/gts-block-unloading-procedure" },
      { name: "Debug Stuck Declaration", slug: "debug-customs-declaration-rfc", url: "/sap-tm/gts-customs/scenarios-troubleshooting/debug-customs-declaration-rfc" },
      { name: "Origin Logic Mixed Goods", slug: "country-of-origin-mixed-goods", url: "/sap-tm/gts-customs/scenarios-troubleshooting/country-of-origin-mixed-goods" },
      { name: "Incoterms Change Impact", slug: "incoterms-change-export-liability", url: "/sap-tm/gts-customs/scenarios-troubleshooting/incoterms-change-export-liability" },
      { name: "Dual-Use Goods Check", slug: "dual-use-goods-check-gts", url: "/sap-tm/gts-customs/scenarios-troubleshooting/dual-use-goods-check-gts" }
    ]
  }
]

export const TM_YL = [
  {
    group: "TM-YL Integration (Basic)",
    category: "basic",
    items: [
      { name: "Yard Request (YR)", slug: "yard-request-definition", url: "/sap-tm/yard-logistics/basic/yard-request-definition" },
      { name: "Yard Order (YO)", slug: "yard-order-definition", url: "/sap-tm/yard-logistics/basic/yard-order-definition" },
      { name: "Yard Task (YT)", slug: "yard-task-definition", url: "/sap-tm/yard-logistics/basic/yard-task-definition" },
      { name: "Check-In Process", slug: "check-in-process-yard", url: "/sap-tm/yard-logistics/basic/check-in-process-yard" },
      { name: "Check-Out Process", slug: "check-out-process-yard", url: "/sap-tm/yard-logistics/basic/check-out-process-yard" },
      { name: "Dock Appointment (DAS)", slug: "dock-appointment-scheduling-das", url: "/sap-tm/yard-logistics/basic/dock-appointment-scheduling-das" },
      { name: "Yard Cockpit", slug: "yard-cockpit-overview", url: "/sap-tm/yard-logistics/basic/yard-cockpit-overview" },
      { name: "Shunting Movement", slug: "shunting-movement-definition", url: "/sap-tm/yard-logistics/basic/shunting-movement-definition" },
      { name: "Weighbridge Int.", slug: "weighbridge-integration-yard", url: "/sap-tm/yard-logistics/basic/weighbridge-integration-yard" },
      { name: "Seal Check", slug: "seal-check-yard-process", url: "/sap-tm/yard-logistics/basic/seal-check-yard-process" }
    ]
  },
  {
    group: "TM-YL Integration (Moderate)",
    category: "moderate",
    items: [
      { name: "Link FO to Yard Request", slug: "link-fo-yard-request-type", url: "/sap-tm/yard-logistics/configuration/link-fo-yard-request-type" },
      { name: "Gate Master Data", slug: "gate-master-data-config", url: "/sap-tm/yard-logistics/configuration/gate-master-data-config" },
      { name: "Time Slot Setup", slug: "time-slot-appointment-setup", url: "/sap-tm/yard-logistics/configuration/time-slot-appointment-setup" },
      { name: "Map Vehicle Resources", slug: "map-vehicle-resources-yl", url: "/sap-tm/yard-logistics/configuration/map-vehicle-resources-yl" },
      { name: "Yard Limit Alerts", slug: "yard-time-limit-alerts", url: "/sap-tm/yard-logistics/configuration/yard-time-limit-alerts" },
      { name: "Mobile App Integration", slug: "yard-mobile-app-integration", url: "/sap-tm/yard-logistics/configuration/yard-mobile-app-integration" },
      { name: "Self-Check-In Kiosk", slug: "self-check-in-kiosk-logic", url: "/sap-tm/yard-logistics/configuration/self-check-in-kiosk-logic" },
      { name: "Door Sync TM-EWM-YL", slug: "door-sync-tm-ewm-yl", url: "/sap-tm/yard-logistics/configuration/door-sync-tm-ewm-yl" },
      { name: "Yard Diagram Config", slug: "yard-diagram-configuration", url: "/sap-tm/yard-logistics/configuration/yard-diagram-configuration" },
      { name: "Yard Capacity Checks", slug: "yard-capacity-checks-config", url: "/sap-tm/yard-logistics/configuration/yard-capacity-checks-config" }
    ]
  },
  {
    group: "TM-YL Integration (Advance)",
    category: "advance",
    items: [
      { name: "Unplanned Arrival DAS", slug: "unplanned-arrival-das-handling", url: "/sap-tm/yard-logistics/scenarios-troubleshooting/unplanned-arrival-das-handling" },
      { name: "TM-YL-EWM Flow", slug: "tm-yl-ewm-integration-flow", url: "/sap-tm/yard-logistics/scenarios-troubleshooting/tm-yl-ewm-integration-flow" },
      { name: "Container Demurrage", slug: "container-storage-demurrage-yard", url: "/sap-tm/yard-logistics/scenarios-troubleshooting/container-storage-demurrage-yard" },
      { name: "Troubleshoot YO Update", slug: "troubleshoot-yo-fo-status-update", url: "/sap-tm/yard-logistics/scenarios-troubleshooting/troubleshoot-yo-fo-status-update" },
      { name: "Multi-Drop Yard Logic", slug: "multi-drop-trucks-yard-logic", url: "/sap-tm/yard-logistics/scenarios-troubleshooting/multi-drop-trucks-yard-logic" }
    ]
  }
]

export const MAIN_NAV_LINKS = [
  { name: "Portfolio", href: "/portfolio" },
  { name: "SAP TM", href: "/sap-tm" },
];


